name: Build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Checkout pico-sdk
      uses: actions/checkout@v4
      with:
        repository: raspberrypi/pico-sdk
        ref: master
        path: pico-sdk
        submodules: true
    - name: Setup cross compiler
      run: |
        sudo apt update
        sudo apt install -y sudo gcc-arm-none-eabi libstdc++-arm-none-eabi-newlib build-essential
    - name: Build
      run: |
        mkdir build
        cd build
        PICO_SDK_PATH=$PWD/../pico-sdk PICO_SDK_BASE=$PWD/../pico-sdk cmake ..
        make -j
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
          name: binaries
          path: build/pico-loongson-ejtag.*
